stages:
  - deploy

job_deploy_master:
  stage: deploy
  only:
    - master
  script:
    - ssh -t -t -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -o 'PubkeyAuthentication yes' -i '/home/gitlab_ci_multi_runner/.ssh/ansibleagent.key' ansibleagent@ws-prod-monitor-01.lanecc.edu 'cd /etc/ansible/roles/aspects_logstash; git fetch origin; git reset --hard origin/master; git submodule update --init; exit;'
  tags:
    - ansible
