---
# set input, output and filter configuration in logstash/conf.d
- name: set defaults
  template:
    src: "defaults.j2"
    dest: "/etc/default/{{ aspects_logstash_options.NAME }}"
  notify:
   - restart logstash
  tags:
    - aspects_logstash
    - aspects_logstash_configtemplates

- name: set patterns
  when: aspects_logstash_rules.patterns is defined
  template:
    src: "patterns.j2"
    dest: "/etc/logstash/patterns"
  notify:
   - restart logstash
  tags:
    - aspects_logstash
    - aspects_logstash_configtemplates

- name: set inputs
  when: aspects_logstash_rules.input is defined
  template:
    src: "input.j2"
    dest: "{{ aspects_logstash_filesystem.conf }}/input.conf"
  notify:
   - restart logstash
  tags:
    - aspects_logstash
    - aspects_logstash_configtemplates

- name: set outputs
  when: aspects_logstash_rules.output is defined
  template:
    src: "output.j2"
    dest: "{{ aspects_logstash_filesystem.conf }}/output.conf"
  notify:
   - restart logstash
  tags:
    - aspects_logstash
    - aspects_logstash_configtemplates

- name: set filters
  when: aspects_logstash_rules.filter is defined
  template:
    src: "filter.j2"
    dest: "{{ aspects_logstash_filesystem.conf }}/filter.conf"
  notify:
   - restart logstash
  tags:
    - aspects_logstash
    - aspects_logstash_configtemplates

- name: copy Elasticsearch template json files
  copy:
    src: "files/elasticsearchTemplates/"
    dest: "/etc/logstash/templates"
  tags:
    - aspects_logstash
    - aspects_logstash_configtemplates
