---
# install tasks.

- name: Untar logstash tarball
  unarchive:
    copy: yes
    src: "downloads/{{ aspects_logstash_bin_filename }}"
    dest: "/opt"
  tags:
    - aspects_logstash
    - aspects_logstash_install
    - aspects_logstash_untar

- name: Symlink logstash home.
  file:
    state="link"
    src="/opt/{{ aspects_logstash_bin_dirname }}"
    dest="/opt/logstash"
  tags:
    - aspects_logstash
    - aspects_logstash_install
