---
- name: restart logstash
  service:
    name: "logstash"
    state: "restarted"
    enabled: "yes"
  tags:
  - aspects_logstash
  - aspects_logstash_configtemplates

- name: reload logstash
  service:
    name: "logstash"
    state: "reloaded"
    enabled: "yes"
  tags:
  - aspects_logstash
  - aspects_logstash_configtemplates

- name: start logstash
  service:
    name: "logstash"
    state: "started"
    enabled: "yes"
  tags:
  - aspects_logstash
  - aspects_logstash_configtemplates

- name: stop logstash
  service:
    name: "logstash"
    state: "stopped"
  tags:
  - aspects_logstash
  - aspects_logstash_configtemplates
